"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowLeft, CheckCircle2, Loader2, Lock, RefreshCw, Save, Send, WifiOff, X } from "lucide-react";
import { toast } from "sonner";
import { detailSurface, dependencyState } from "@/lib/task-ui-state";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Textarea } from "../ui/textarea";

type Issue={id:string;ref:string;title:string;detail:string;status:string;priority:string;stage:string;assigneeAgentId:string|null;parentId:string|null;blockedBy:string[];runId:string|null;summary:string;createdAt:number;updatedAt:number};
type Data={issue:Issue;project:{name:string;path:string;branch?:string|null};agents:Array<{id:string;name:string}>;issues:Issue[];children:Issue[];blockedBy:Issue[];blocking:Issue[];comments:Array<{id:string;authorType:string;body:string;createdAt:number}>;documents:Array<{key:string;body?:string;revision?:number}>;approvals:Array<{id:string;type:string;status:string;payload:unknown}>;runs:Array<{id:string;status:string;source:string;error?:string|null;startedAt:number;finishedAt?:number|null;usage:Record<string,unknown>}>;activity:Array<{id:string;actorType:string;action:string;createdAt:number}>;usage:Array<{id:string;model:string;inputTokens:number;outputTokens:number;cost:number}>};
const STATUSES=["backlog","todo","in_progress","in_review","blocked","done","cancelled"], PRIORITIES=["urgent","high","medium","low"], STAGES=["plan","execute","integrate"];
const when=(n?:number|null)=>n?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(n):"—";
function Select(p:React.ComponentProps<"select">){return <select {...p} className="h-9 w-full rounded-md border border-line-strong bg-paper-white px-2.5 text-[12px] outline-none focus:border-electric-indigo"/>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border border-line bg-paper-white"><h2 className="border-b border-line px-4 py-3 text-[12px] font-medium">{title}</h2><div className="p-4">{children}</div></section>}
function DepStatus({status}:{status:string}){const done=status==="done";return <span className={"shrink-0 rounded px-1.5 py-0.5 text-[10px] font-medium "+(done?"bg-lichen-green/15 text-lichen-green":status==="cancelled"?"bg-code-surface text-pebble":"bg-amber-50 text-amber-800")}>{done?"resolved":status.replace("_"," ")}</span>}

export function IssueDetail({id}:{id:string}){
 const router=useRouter(),[data,setData]=useState<Data|null>(null),[state,setState]=useState<"loading"|"online"|"disconnected"|"error">("loading"),[comment,setComment]=useState(""),[child,setChild]=useState(""),[docs,setDocs]=useState<Record<string,string>>({}),[saving,setSaving]=useState("");
 const load=useCallback(async(quiet=false)=>{if(!quiet)setState("loading");try{const r=await fetch("/api/issues/"+id,{cache:"no-store"});if(!r.ok)throw new Error();const n=await r.json() as Data;setData(n);setDocs(c=>({plan:c.plan??n.documents.find(d=>d.key==="plan")?.body??"",output:c.output??n.documents.find(d=>d.key==="output")?.body??""}));setState("online")}catch{setState(c=>c==="online"||c==="disconnected"?"disconnected":"error")}},[id]);
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(true),5000);return()=>clearInterval(t)},[load]);
 async function save(p:Partial<Issue>){if(!data)return;const old=data;setData({...data,issue:{...data.issue,...p}});setSaving("properties");try{const r=await fetch("/api/issues",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...p})}),j=await r.json();if(!r.ok)throw new Error(j.error??"Update rejected");setData(c=>c?{...c,issue:j.issue}:c)}catch(e){setData(old);toast.error("Update rolled back",{description:e instanceof Error?e.message:"Server rejected the change"})}finally{setSaving("")}}
 async function act(body:Record<string,unknown>,label:string){setSaving(label);try{const r=await fetch("/api/issues/"+id,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error??"Request rejected");await load(true);return true}catch(e){toast.error(label+" failed",{description:e instanceof Error?e.message:"Try again"});return false}finally{setSaving("")}}
 const thread=useMemo(()=>data?[...data.comments.map(x=>({id:x.id,type:x.authorType,body:x.body,createdAt:x.createdAt})),...data.activity.map(x=>({id:x.id,type:"system",body:x.action.replaceAll("."," "),createdAt:x.createdAt}))].sort((a,b)=>a.createdAt-b.createdAt):[],[data]);
 const surface=detailSurface(state,Boolean(data));
 if(surface==="loading")return <div className="flex flex-1 items-center justify-center text-pebble"><Loader2 className="mr-2 size-4 animate-spin"/>Loading canonical issue…</div>;
 if(surface==="error"||!data)return <div className="flex flex-1 flex-col items-center justify-center gap-3"><AlertTriangle className="text-alarm-red"/><p>Issue detail is unavailable.</p><Button onClick={()=>void load()}><RefreshCw/>Retry</Button></div>;
 const i=data.issue, possible=data.issues.filter(x=>x.id!==i.id&&!i.blockedBy.includes(x.id)),dep=dependencyState(data.blockedBy.map(x=>x.status)),input=data.usage.reduce((s,x)=>s+x.inputTokens,0),output=data.usage.reduce((s,x)=>s+x.outputTokens,0),cost=data.usage.reduce((s,x)=>s+x.cost,0);
 return <div className="scroll-thin flex h-full min-w-0 flex-1 flex-col overflow-y-auto">
  <header className="sticky top-0 z-10 flex items-center gap-3 border-b border-line bg-warm-bone/95 px-6 py-3 backdrop-blur"><button aria-label="Back to board" onClick={()=>router.push("/board")}><ArrowLeft className="size-4"/></button><span className="font-mono text-[11px] text-pebble">{i.ref}</span><span className={"flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] "+(i.status==="blocked"?"bg-amber-50 text-amber-800":"bg-mist-lavender text-electric-indigo")}>{i.status==="blocked"&&<Lock className="size-2.5" aria-hidden/>}{i.status}</span>{saving&&<span className="ml-auto flex items-center gap-1 text-[11px] text-pebble"><Loader2 className="size-3 animate-spin"/>Saving {saving}…</span>}</header>
  {state==="disconnected"&&<div role="alert" className="flex justify-between bg-amber-50 px-6 py-2 text-[12px] text-amber-900"><span className="flex gap-2"><WifiOff className="size-4"/>Disconnected. Showing the last server state.</span><button onClick={()=>void load()}>Reconnect</button></div>}
  <main className="mx-auto grid w-full max-w-[1280px] grid-cols-1 gap-4 p-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-4">
   <Section title="Issue"><Input aria-label="Issue title" defaultValue={i.title} onBlur={e=>e.target.value!==i.title&&void save({title:e.target.value})} className="mb-3 border-transparent px-1 text-[20px] font-medium shadow-none"/><Textarea aria-label="Issue description" defaultValue={i.detail} onBlur={e=>e.target.value!==i.detail&&void save({detail:e.target.value})} placeholder="Add a description…" className="min-h-28"/>{i.summary&&<p className="mt-3 rounded-lg bg-code-surface p-3 text-[12px]">{i.summary}</p>}</Section>
   <Section title="Human, agent & system thread"><div className="space-y-3">{thread.map(x=><div key={x.id} className="border-l-2 border-line pl-3"><div className="flex justify-between text-[10px] uppercase text-pebble"><span>{x.type}</span><span>{when(x.createdAt)}</span></div><p className="whitespace-pre-wrap text-[13px]">{x.body}</p></div>)}{!thread.length&&<p className="text-[12px] text-pebble">No activity yet.</p>}</div><div className="mt-4 flex gap-2"><Textarea aria-label="New comment" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment…"/><Button aria-label="Post comment" disabled={!comment.trim()} onClick={async()=>{if(await act({action:"comment",body:comment},"comment"))setComment("")}}><Send/></Button></div></Section>
   <Section title="Child tree"><div className="space-y-1">{data.children.map(x=><button key={x.id} onClick={()=>router.push("/board/"+x.id)} className="flex w-full justify-between rounded-lg border border-line px-3 py-2 text-[12px] hover:bg-code-surface"><span>{x.ref} · {x.title}</span><span className="text-pebble">{x.status}</span></button>)}{!data.children.length&&<p className="text-[12px] text-pebble">No child issues.</p>}</div><div className="mt-3 flex gap-2"><Input aria-label="New child issue title" value={child} onChange={e=>setChild(e.target.value)} placeholder="New child issue"/><Button variant="outline" disabled={!child.trim()} onClick={async()=>{if(await act({action:"child",title:child},"child"))setChild("")}}>Add</Button></div></Section>
   <Section title="Dependencies">
    {dep.total>0&&(dep.open>0
     ?<div className="mb-4 flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-amber-900"><Lock className="mt-0.5 size-4 shrink-0"/><div><p className="text-[12px] font-medium">Blocked — waiting on {dep.open} of {dep.total} {dep.total===1?"dependency":"dependencies"}</p><p className="mt-0.5 text-[11px] text-amber-800">This issue can&apos;t start until every dependency is done. Finish or remove the open blockers below to unblock it.</p></div></div>
     :<div className="mb-4 flex gap-2 rounded-lg border border-lichen-green/30 bg-lichen-green/10 p-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-lichen-green"/><div><p className="text-[12px] font-medium text-lichen-green">Ready — all {dep.total} {dep.total===1?"dependency is":"dependencies are"} resolved</p><p className="mt-0.5 text-[11px] text-bark-grey">Nothing is holding this issue back; an assigned agent can pick it up.</p></div></div>)}
    <div className="grid gap-4 sm:grid-cols-2">
     <div><p className="label mb-2">Blocked by · needs these done first</p><div className="space-y-1.5">{data.blockedBy.map(x=><div key={x.id} className="flex items-center gap-2 rounded-lg border border-line px-2.5 py-1.5"><button onClick={()=>router.push("/board/"+x.id)} className="min-w-0 flex-1 truncate text-left text-[12px] text-sapphire-link" title={x.ref+" · "+x.title}>{x.ref} · {x.title}</button><DepStatus status={x.status}/><button aria-label={"Remove blocker "+x.ref} title="Remove this dependency" onClick={()=>void save({blockedBy:i.blockedBy.filter(id=>id!==x.id)})} className="shrink-0 rounded p-0.5 text-pebble hover:bg-code-surface hover:text-alarm-red"><X className="size-3.5"/></button></div>)}{!data.blockedBy.length&&<p className="text-[12px] text-pebble">No dependencies — nothing is blocking this issue.</p>}</div></div>
     <div><p className="label mb-2">Blocking · these wait on this issue</p><div className="space-y-1.5">{data.blocking.map(x=><div key={x.id} className="flex items-center gap-2 rounded-lg border border-line px-2.5 py-1.5"><button onClick={()=>router.push("/board/"+x.id)} className="min-w-0 flex-1 truncate text-left text-[12px] text-sapphire-link" title={x.ref+" · "+x.title}>{x.ref} · {x.title}</button><DepStatus status={x.status}/></div>)}{!data.blocking.length&&<p className="text-[12px] text-pebble">This issue isn&apos;t blocking anything.</p>}</div></div>
    </div>
    <Select aria-label="Add a blocker" className="mt-3" value="" onChange={e=>e.target.value&&void save({blockedBy:[...i.blockedBy,e.target.value]})}><option value="">Add a dependency…</option>{possible.map(x=><option key={x.id} value={x.id}>{x.ref} · {x.title}</option>)}</Select>
   </Section>
   {["plan","output"].map(k=><Section key={k} title={k[0].toUpperCase()+k.slice(1)+" document · revision "+(data.documents.find(d=>d.key===k)?.revision??0)}><Textarea aria-label={k+" document"} value={docs[k]??""} onChange={e=>setDocs(c=>({...c,[k]:e.target.value}))} className="min-h-40 font-mono text-[12px]"/><Button className="mt-3" variant="outline" onClick={()=>void act({action:"document",key:k,body:docs[k]??""},k)}><Save/>Save {k}</Button></Section>)}
   <Section title="Approval cards"><div className="space-y-2">{data.approvals.map(a=><div key={a.id} className="rounded-lg border border-line p-3"><div className="flex justify-between text-[12px]"><b>{a.type}</b><span>{a.status}</span></div><pre className="mt-2 whitespace-pre-wrap text-[11px]">{JSON.stringify(a.payload,null,2)}</pre>{a.status==="pending"&&<div className="mt-2 flex gap-2"><Button size="sm" onClick={()=>void act({action:"approval",approvalId:a.id,decision:"approved"},"approval")}>Approve</Button><Button size="sm" variant="outline" onClick={()=>void act({action:"approval",approvalId:a.id,decision:"rejected"},"approval")}>Reject</Button></div>}</div>)}{!data.approvals.length&&<p className="text-[12px] text-pebble">No approval requests.</p>}</div></Section>
   <Section title="Run ledger"><div className="space-y-1">{data.runs.map(r=><div key={r.id} className="grid grid-cols-[1fr_90px_150px] gap-2 rounded border border-line px-3 py-2 text-[11px]"><span className="truncate font-mono">{r.id}</span><span>{r.status}</span><span>{when(r.startedAt)}</span>{r.error&&<span className="col-span-3 text-alarm-red">{r.error}</span>}</div>)}{!data.runs.length&&<p className="text-[12px] text-pebble">No runs recorded.</p>}</div></Section>
  </div><aside className="space-y-4">
   <Section title="Editable properties"><div className="space-y-3"><label className="block"><span className="label">Status</span><Select value={i.status} onChange={e=>void save({status:e.target.value})}>{STATUSES.map(x=><option key={x}>{x}</option>)}</Select></label><label className="block"><span className="label">Assignee</span><Select value={i.assigneeAgentId??""} onChange={e=>void save({assigneeAgentId:e.target.value||null})}><option value="">Unassigned</option>{data.agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></label><label className="block"><span className="label">Priority</span><Select value={i.priority} onChange={e=>void save({priority:e.target.value})}>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</Select></label><label className="block"><span className="label">Stage</span><Select value={i.stage} onChange={e=>void save({stage:e.target.value})}>{STAGES.map(x=><option key={x}>{x}</option>)}</Select></label></div></Section>
   <Section title="Timestamps"><dl className="space-y-2 text-[11px]"><div className="flex justify-between"><dt>Created</dt><dd>{when(i.createdAt)}</dd></div><div className="flex justify-between"><dt>Updated</dt><dd>{when(i.updatedAt)}</dd></div></dl></Section>
   <Section title="Workspace & branch"><dl className="space-y-2 text-[11px]"><dt className="text-pebble">Project</dt><dd>{data.project.name}</dd><dt className="text-pebble">Workspace</dt><dd className="break-all font-mono">{data.project.path}</dd><dt className="text-pebble">Branch</dt><dd className="font-mono">{data.project.branch??"unavailable"}</dd><dt className="text-pebble">Checkout</dt><dd className="break-all font-mono">{i.runId??"none"}</dd></dl></Section>
   <Section title="Usage"><dl className="space-y-2 text-[11px]"><div className="flex justify-between"><dt>Input</dt><dd>{input.toLocaleString()}</dd></div><div className="flex justify-between"><dt>Output</dt><dd>{output.toLocaleString()}</dd></div><div className="flex justify-between"><dt>Cost</dt><dd>{"$"+cost.toFixed(4)}</dd></div></dl></Section>
  </aside></main>
 </div>
}
